language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools
  - android-30
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_0d6d62930b50_key -iv $encrypted_0d6d62930b50_iv
  -in exception-catcher.jks.enc -out exception-catcher.jks -d
